title: Benoit Viguier

#Override it in sculpin_site_dev.yml (see README)
hidden:
  phone: 06________
  address: ________
  email: ____@__.com

degrees:
  -
    name: Doctorant en Informatique
    year: 2008
    university: Université Claude Bernard Lyon 1 (UCBL)
    special:
  -
    name: Master Recherche, Spécialité Image et Informatique Graphique
    year: 2006
    university: UCBL (Lyon2, INSA, ECL, ENS)
    special: Mention Bien
  -
    name: Maitrise d'Informatique
    year: 2005
    university: UCBL
    special: Mention Bien
  -
    name: Licence d'Informatique
    year: 2004
    university: UCBL
    special: Mention Très Bien
  -
    name: DEUG Mathématiques, Informatique et Application aux Sciences
    year: 2005
    university: UCBL
    special: 16e/207

hobbies:
  Musique:
    - Saxophone (3e prix Européen de saxophone, à Gap en 1998), Clavier
    - Participation à diverses formations (Orchestre de Bal, Jazz Group, BigBand)
    - Musique Assistée par Ordinateur
  Divers:
    - Veille technologique (livres, conférences)
    - Casse-têtes, Jeux vidéos
    - Badminton
    - Magie des pièces

links:
  -
    name: 3DReshaper Dental
    url: http://www.3dreshaper-dental.com
    short_url: bit.ly/1EKbaQJ
    image: Dental.PNG
    description: Le logiciel de CAO dentaire développé chez Technodigit
  -
    name: Convergences
    url: https://www.youtube.com/watch?v=UDT2j8iLlRc
    short_url: bit.ly/N6PSgc
    image: Convergences.PNG
    description: Présentation du projet Convergences développé chez Phoenix Interactive
  -
    name: Article
    url: http://liris.cnrs.fr/Documents/Liris-3285.pdf
    short_url: bit.ly/PmJjFK
    image: ArticleLiris.PNG
    description: Mes travaux sur la modélisation d’un système de lumière structurée à partir de graphes, lors de ma thèse au Liris

socials:
  Twitter:
    icon: twitter-square
    alias: @b_viguier
    url: https://twitter.com/b_viguier
  Github:
    icon: github-square
    alias: @b-viguier
    url: https://github.com/b-viguier
  Linkedin:
    icon: linkedin-square
    alias: linkedin.com/in/bviguier
    url: https://fr.linkedin.com/in/bviguier
