title: Benoit Viguier

#Override it in sculpin_site_dev.yml (see README)
hidden:
  phone: 06________
  address: ________
  email: ____@__.com

degrees:
  -
    name: Doctorant en Informatique
    year: 2008
    university: Ucb Lyon 1
    special: Thèse non soutenue suite à embauche
  -
    name: Master Recherche, Image et Informatique Graphique
    year: 2006
    university: Ucb Lyon 1
    special: Mention Bien
  -
    name: Maitrise d'Informatique
    year: 2005
    university: Ucb Lyon 1
    special: Mention Bien
  -
    name: Licence d'Informatique
    year: 2004
    university: Ucb Lyon 1
    special: Mention Très Bien
  -
    name: DEUG Mathématiques, Informatique et Application aux Sciences
    year: 2003
    university: Ucb Lyon 1
    special: 16e/207

hobbies:
  Musique:
    - Saxophone (3e prix Européen de saxophone, à Gap en 1998), Clavier
    - Participation à diverses formations (Orchestre de Bal, Jazz Group, BigBand)
    - Musique Assistée par Ordinateur
  Divers:
    - Veille technologique (livres, conférences)
    - Casse-têtes, Jeux vidéos
    - Badminton
    - Magie des pièces

socials:
  Website:
    icon: globe
    alias: b-viguier.github.io
    url: https://b-viguier.github.io
  Twitter:
    icon: twitter-square
    alias: twitter.com/b_viguier
    url: https://twitter.com/b_viguier
  Github:
    icon: github-square
    alias: github.com/b-viguier
    url: https://github.com/b-viguier
  Linkedin:
    icon: linkedin-square
    alias: linkedin.com/in/bviguier
    url: https://fr.linkedin.com/in/bviguier

skills:
  -
    title: Maîtrise
    icons: [star, star, star, star-half-o]
    list:
      - C++
      - Php
      - Qt Framework
      - Git
      - Mercurial
      - Design Pattern
  -
    title: Utilise
    icons: [star, star, star-half-o, star-o]
    list:
      - Javascript
      - Symfony2
      - MySql
      - OpenGL
      - Tests unitaires
  -
    title: Aimerait
    icons: [heart, heart, heart, heart]
    list:
      - Go
      - iOS / Android
      - Open Source
